### ISSUE TITLE
obtain data for constrained optimization task

### ISSUE THREAD

**Issue by giame** [divelab/DIG#100]
for the constrained optimization task there is only ZINC dataset: zinc_800_graphaf.csv 

how to obtain this same csv on moses and qm9?
is this given from the output from the property optimization task?
thanks!

**Comment by mengliu1998** [comment]
Hi @giame,

Thank you for your interest. We only provide the API of ZINC for constrained optimization in DIG, since this is the most commonly used setting in the graph generation community. You can find the cvs files on MOSES and QM9 at [here](https://github.com/divelab/DIG_storage/tree/main/ggraph).
