### ISSUE TITLE
Installation of Packages

### ISSUE THREAD

**Issue by MITRA-S** [divelab/DIG#11]
Hello,
I wish to use sslgraph from DIG. 
I downloaded the codes from github. However, I cannot install the packages  by doing 
pip install git+git://github.com/divelab/DIG.git ,
inside a conda environment.
This immediately gives errors. 
ERROR: Command errored out with exit status1: python setup.py egg_info Check the logs for full command output.

Do you have suggestions? Is there a setup.py file available?
Thank you,
Saheli

**Comment by mengliu1998** [comment]
Thank you for your question.

Currently, our code has not been organized as a PyPi package yet. To use it, you can just go to the sslgraph directory (https://github.com/divelab/DIG/tree/main/dig/sslgraph), and there are several examples/tutorials. The environmental requirement for sslgraph is listed in README.md in the directory of sslgraph, and it is just PyTorch and PyTorch Geometric.

We are organizing the code to form a PyPi package so that users can install it through 'pip'. That version will be available soon.

If you have any further questions, please let me know.

Thank you.

**Comment by MITRA-S** [comment]
Hi,
Thanks,
it worked!
Saheli
