### ISSUE TITLE
PGExplainer graph visualization

### ISSUE THREAD

**Issue by alirezadizaji** [divelab/DIG#118]
there is a problem in pgexplainer graph visualization as in `plot_bashapes`, 'node_idx' and 'y' must be filled within `kwargs`, though during visualization for graph explanation there is no passing of them

**Comment by Oceanusity** [comment]
Thank you for your issue. Since `ba_shapes` is a node classification dataset, please specify the `explain_graph=False`. In the [visualization](https://github.com/divelab/DIG/blob/db81355aa7b3da46b37b41da9d7caaeb7105b6fd/dig/xgraph/method/pgexplainer.py#L805) for node classification, the parameter `y` can be obtained from the data.
