### ISSUE TITLE
Captum version requirement outdated?

### ISSUE THREAD

**Issue by jan0b** [divelab/DIG#141]
The version requirement for captum is **captum==0.2.0**. As version 0.5.0 is already published, is there any specific reason for the strong version requirement in DIG?

**Comment by CM-BF** [comment]
> The version requirement for captum is **captum==0.2.0**. As version 0.5.0 is already published, is there any specific reason for the strong version requirement in DIG?

In our code, some **low-level functions** in `capture` are used to construct graph-specific explainers. The cost of updating it to a newer version is high since it is not as easy as "changing the high-level API signature". We won't change its version without necessity.

Please let me know if any questions!
