### ISSUE TITLE
About torch-geometric version

### ISSUE THREAD

**Issue by orientalCherry841** [divelab/DIG#165]
When I used the **torch-geometric2.1.0,** I meet such an error:
**ModuleNotFoundError: No module named 'torch_geometric.nn.acts'**
Then, I did find thah there are really no acts in this version.
Next, I download **torch-geometric2.0.4**, the previous error is gone. But, I meet a new error:
**AttributeError: Can't get attribute 'DataEdgeAttr' on <module 'torch_geometric.data.data'** from '/home/cuisx/anaconda3/envs/pytorch2_copy/lib/python3.8/site-packages/torch_geometric-2.0.4-py3.8.egg/torch_geometric/data/data.py'>
It seems to be caused by "version dependency".
When I used torch-geometric2.1.0, I don't have this error. I have no idea how to sovle this problem. It looks like neither version will work.

**Comment by lyzustc** [comment]
Hi, @orientalCherry841, thank you for reporting the error. The problem with torch-geometric2.1.0 is similar to [this issue](https://github.com/divelab/DIG/issues/156), due to that swish cannot be imported from the latest pyg. We have fixed this problem in the [latest commit](https://github.com/divelab/DIG/commit/575b9c10e71f6e1f82a8f95ca0027c49bda71afa) and you may check whether torch-geometric2.1.0 works for you now.

**Comment by orientalCherry841** [comment]
Thanks a lot. I solved the problem using the solution presented in that issue.
