### ISSUE TITLE
Generate graphs for non-chemical domains

### ISSUE THREAD

**Issue by AresEkb** [divelab/DIG#180]
Hi

Is it possible to generate generic graphs (for example, process models) using DIG? All examples seems to be chemistry-related.

**Comment by lyzustc** [comment]
Hi,

Thanks for your interest in our package! The graph generation codes are designed for molecular graph generation problems since currently most research literatures in graph generation are about molecular graphs. Generating other graphs cannot be done by directly using the codes in DIG. To train a generative model for these graphs, you may need to implement your graph data interface and loader and remove chemical related codes (such as bond valency check) in graph generation method implementations.

**Comment by AresEkb** [comment]
Thanks for the answer! I didn't found yet any ready to use generic graph generators. Maybe I'll try to adapt the library code or wait for developments in this area...
