### ISSUE TITLE
How can I get the vectors of the SphereNet representaions (such as the dist_emb, angle_emb, torsion_emb)

### ISSUE THREAD

**Issue by jonejunzhang** [divelab/DIG#202]

**Comment by limei0307** [comment]
Hi @jonejunzhang, the variable `emb` in [this line](https://github.com/divelab/DIG/blob/dig-stable/dig/threedgraph/method/spherenet/spherenet.py#L292) should include the dist_emb, angle_emb, and torsion_emb of the input batch. This is because the [forward function here](https://github.com/divelab/DIG/blob/dig-stable/dig/threedgraph/method/spherenet/spherenet.py#L28) can return these representations.

**Comment by jonejunzhang** [comment]
@limei0307 Your soonest response will be highly appreciated.

**Comment by limei0307** [comment]
Hi @jonejunzhang, could you please provide more details about your question? I want to make sure that I fully understand your concern. Based on my current understanding, I believe I have already provided an answer in my previous reply. 

To clarify, the variable `emb` in [this line](https://github.com/divelab/DIG/blob/dig-stable/dig/threedgraph/method/spherenet/spherenet.py#L292) should include the dist_emb, angle_emb, and torsion_emb of the input batch. You can print out the save the variable `emb`, and this should include the vectors you need.

In addition, the trained SphereNet models on QM9 and MD17 are provided [here](https://github.com/divelab/DIG_storage/tree/main/3dgraph). You can load the trained models to get the vectors and make predictions.

**Comment by jonejunzhang** [comment]
OK, many thanks for your help.
