### ISSUE TITLE
Questions about the ComENet

### ISSUE THREAD

**Issue by StefanIsSmart** [divelab/DIG#233]
1. Can ComENet distinguish chiral conformations?
2. Why is ComENet's more complete representation not as good as SphereNet? It stands to reason that ComENet contains a larger amount of information.

**Comment by limei0307** [comment]
Hi @StefanIsSmart, 

Thanks for your interest in our work.

1. Yes, ComENet can distinguish chiral conformations since it also considers the angle $\phi$, similar to SphereNet. [Table 6 of our new survey paper](https://arxiv.org/abs/2307.08423) shows the difference between SphereNet and ComENet. 
2. About the experimental performance: This is a very good point. We were thinking about this. I think there are several reasons.
  - Datasets: We tested ComENet on three datasets - QM9, Molecule3D, and OC20. Among these three datasets, only OC20 contains different conformers for the same molecule, as shown in [Section 6.4 of our paper](https://openreview.net/forum?id=mCzMqeWSFJ), and ComENet performs better than SphereNet on this dataset.
  -   Practically, we use cutoff (e.g. 5A) to define edges, therefore, we consider more edges than chemical bonds. If we consider a large number of edges, SphereNet is already complete in many cases. Theoretically, we have to emphasize that, there are some cases that SphereNet can not distinguish, but ComENet is complete and can distinguish all cases.
  - Edge-based vs node-based message passing: SphereNet uses directional message passing (update message on each edge, high complexity) while ComENet uses node-based message passing. In ComENet, edge features are fixed and not learned. This may limit the model's performance but can improve efficiency.

Let us know if you have other questions. Thanks.

**Comment by 11140321** [comment]
Hello, I have some problems with the use of this code. Have you run it successfully? The article only says that protein processing is carried out at three different levels, but there are many folders in the code. I am not sure what they are. What does it mean, and how does the processing work? Could you please give me an answer?

**Comment by StefanIsSmart** [comment]
Thank you for your reply! Also thank you for your work! It is really useful for me!

But I have one more question:

When I use the ComENet to do some tasks. For example, I use a learnable token to mask some position information as the input position Info. for ComENet. That means the input position Info. will require grads. 
The first iteration is okay, but after we did the backward() and step() ,  the nan will happen.
This question only happened when I used ComENet, the other networks like EGNN did nothing wrong.

I don't know why, could you give me a favor?

**Comment by limei0307** [comment]
Hi @StefanIsSmart, 

Based on my experience, in most cases, nan happens when divided by zero. [dist_ji here](https://github.com/divelab/DIG/blob/dig-stable/dig/threedgraph/method/comenet/comenet.py#L371) is used as the denominator in lines 375 and 383, so please try to add a small eps (e.g. 1e-6) to dist_ji to make sure the value is larger than 0.

Another difference between ComENet and other methods is that it selects some reference nodes based on distance values as shown [here](https://github.com/divelab/DIG/blob/dig-stable/dig/threedgraph/method/comenet/comenet.py#L304-L327). I am not sure if this affects your method. 

Let us know if you have other questions. Thanks.

**Comment by StefanIsSmart** [comment]
> Hi @StefanIsSmart,
> 
> Based on my experience, in most cases, nan happens when divided by zero. [dist_ji here](https://github.com/divelab/DIG/blob/dig-stable/dig/threedgraph/method/comenet/comenet.py#L371) is used as the denominator in lines 375 and 383, so please try to add a small eps (e.g. 1e-6) to dist_ji to make sure the value is larger than 0.
> 
> Another difference between ComENet and other methods is that it selects some reference nodes based on distance values as shown [here](https://github.com/divelab/DIG/blob/dig-stable/dig/threedgraph/method/comenet/comenet.py#L304-L327). I am not sure if this affects your method.
> 
> Let us know if you have other questions. Thanks.

I find the calculation of phi and tau will get the nan number in the backward() grad.
The distance and the theta calculation is nothing wrong.
I have no idea how to solve this bug....

**Comment by limei0307** [comment]
Have you tried to add a small eps (e.g. 1e-6) to [dist_ji](https://github.com/divelab/DIG/blob/dig-stable/dig/threedgraph/method/comenet/comenet.py#L371) to make sure the value is larger than 0?

**Comment by StefanIsSmart** [comment]
Have you tried to add a small eps (e.g. 1e-6) to [dist_ji](https://github.com/divelab/DIG/blob/dig-stable/dig/threedgraph/method/comenet/comenet.py#L371) to make sure the value is larger than 0?

Thank you, I have solved this question.
Adding a small eps to 0 is not enough, because some values like 1e-20 are close to 0 and will cause the nan.
