### ISSUE TITLE
Optimal parameter set for SchNet in QM9/MD17 tasks?

### ISSUE THREAD

**Issue by colormeblue1013** [divelab/DIG#59]
Hey, I was wondering if you had or know where to find the optimal parameter set for SchNet. 
Thanks for your work.

**Comment by limei0307** [comment]
Hi @colormeblue1013 ,

You can find the trained model for SchNet [here](http://www.quantum-machine.org/datasets/trained_schnet_models.zip) and there is [an example code on QM9](https://github.com/pyg-team/pytorch_geometric/blob/master/examples/qm9_pretrained_schnet.py) in pytorch geometric. 

Since pytroch geometric  includes some trained models and example codes for SchNet and DimeNet, we do not provide these in our code.

Besides, you can find the trained model for SphereNet [here](https://github.com/divelab/DIG_storage/tree/main/3dgraph/qm9).

Thanks!

**Comment by colormeblue1013** [comment]
Thanks for your prompt reply. It's really helpful for me!
