### ISSUE TITLE
Bug in spherenet feature.py

### ISSUE THREAD

**Issue by Franklalalala** [divelab/DIG#61]
https://github.com/divelab/DIG/blob/1c3dd70d5ae9887c61d7c6b37f31c6433cfe0c07/dig/threedgraph/method/spherenet/features.py#L185

The zero order of first kind bessel function is  sin(freq * x) / x
Here is sin(freq * x)
Is this a bug?

**Comment by limei0307** [comment]
Hi @Franklalalala,

I think there is '/x' in the envelope function. Thus this is meaningful.
We removed the envelope function in the angle_emb and torsion_emb functions since the '/x' in the envelope function leads to an incorrect spherical basis layer as mentioned [here(second point)](https://github.com/klicperajo/dimenet/blob/master/README.md#known-issues).

Thanks
