### ISSUE TITLE
dynamic graph

### ISSUE THREAD

**Issue by dialuser** [divelab/DIG#8]
HI, I wonder if the XGNN toolkit can be applied to graphs with temporally varying features. Currently, my model was trained using GCN-LSTM algorithm, for a regression problem, not classification. Thanks ahead.

**Comment by Nate1874** [comment]
Thanks for your question.  
We have not explored any temporal graph data yet. From my understanding, if the graph (nodes/edges) are fixed and only the features are temporally varying, you can apply our XGNN by generating the graph structures for a particular interval in your regression. You can focus on generating the graph structure for time step 0 and feed to the GCN-LSTM. In addition, you may need to modify the policy network to consider the temporal information.

**Comment by dialuser** [comment]
Nate, thank you for the response. Yes, for now the graph topology may be considered fixed and only features are temporally varying in my problem. I looked into XGNN. I have two questions: 
(a) I'm thinking to replace BCE with a regression metric, e.g., R2 or MSE, when calculating reward.  Is there anything else I need to change?
(b) I already have a trained GCN-LSTM model and I'd like to know which features were more influential. Can I apply the XGNN using this trained model? Based on your paper, it seems many other tools in the explainable GNN toolbox are not suitable for complex GNN architecture(?)

**Comment by Nate1874** [comment]
(a). First, it depends on your task. What target do you try to explain? The reward needs to corresponds to the target. For example, if you wish to study what graph patterns can lead to regression score  6. Then you need to design the reward to encourage the generated graphs to obtain closer scores to the target score 6. 

(b). I am not sure what's the meaning of "which features were more influential". In most cases, we study which features were more influential for each input graph since different features may contribute differently for different input graphs, which are the instance-level explanations. Then XGNN is not suitable since XGNN only provide model-level explanations.

**Comment by dialuser** [comment]
Thanks for the clarifications. In my case, each feature represents the effect of certain physics. My intuition is that certain features are more important than others. Assuming each time represents a separate graph instance, I'm interested in the feature importance on a time-averaged sense, but I understand now that XGNN does not offer mask for node features.
