### ISSUE TITLE
How to visualize the saved searching results

### ISSUE THREAD

**Issue by Zha0nin9-Yu** [divelab/DIG#86]
Hi,

I am trying to visualize all saved searching results of mutag dataset.
However, when I am loading those pt files using torch.load().
It shows ModuleNotFoundError: No module named 'pipeline'.
Could you help me with that?

Thank you

**Comment by Oceanusity** [comment]
Hello, thank you for your issue. In order to reproduce the provided results, please follow the code in the [main branch](https://github.com/divelab/DIG/tree/main/dig/xgraph/SubgraphX).

The reason for the pipeline is that the saved results saving the whole class of MCTS_Node with the path pipeline.py. Therefore, a file with such a class is required. [ref](https://github.com/divelab/DIG/blob/main/dig/xgraph/SubgraphX/pipeline.py).

The second one is a version issue. Please follow the version in the [install.sh](https://github.com/divelab/DIG/blob/main/dig/xgraph/SubgraphX/install.sh).
