### ISSUE TITLE
[Feature Request] Extending Graph Explainability for 3D Graphs

### ISSUE THREAD

**Issue by merdivane** [divelab/DIG#94]
Hi, 
I would like to use the methods in xgraph modules for 3D graphs such as SchNet and DimenetPP. Particularly I am interested in SubgraphX. I had to modify quite a few parts to use in my code but I would like to ask if you would consider to add the Feature: Graph Explainability for 3D graphs covering other models as well.

Thank you very much for the repo and your time.

**Comment by mengliu1998** [comment]
Hi @merdivane,

Thank you for your interest and constructive question. We are currently adding the direction of 3D graph generation. We are definitely interested in explainability methods on 3D graphs. To our knowledge, this direction is really under-explored. Are you aware of any methods in explainability for 3D graph networks? 

Thank you.

**Comment by merdivane** [comment]
Hello again, 
I am not aware any explainability method for specifically for 3D graphs. My first thought was to just change model(x,edge_index) to model(x,pos,edge_index) and use subgraphX as it is.  Do you think it makes sense?

**Comment by mengliu1998** [comment]
Hi @merdivane,

To our knowledge, there does not exist any approaches for explaining 3D graph networks. I **personally** believe that we should design specific novel explainability methods for 3D graph networks instead of directly extending methods on 2D graphs. In terms of your thought, the difficult part could be that the pos is a continuous variable.

We will definitely considering adding this direction when it is well-formulated since it is highly related to the scope of DIG.

Thank you and I am happy to have any further discussions.
